name: Manual workflow for Azure KV testing

on:
  workflow_dispatch:
    inputs:
      client-id:
        description: "Azure client id"
        required: true
        type: string
      tenant-id:
        description: "Azure tenant id"
        required: true
        type: string
      subscription-id:
        description: "Azure subscription id"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  
jobs:
  kv-test:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login via OIDC
        uses: Azure/login@v1
        with:
          enable-oidc: true
          client-id: ${{ inputs.client-id }}
          tenant-id: ${{ inputs.tenant-id }}
          subscription-id: ${{ inputs.subscription-id }}

      - name: Fetch secrets from Key Vault
        id: kv
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ibarulin-test-kv
          secrets: |
            test-key

      - name: Test result
        run: echo ${{ steps.kv.outputs.test-key }}
